pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    // Configurar o ambiente de compilação
                    def mvnHome = tool 'Maven 3.9.5'
                    env.PATH = "${mvnHome}/bin:${env.PATH}"

                    // Verificar o sistema operacional
                    def isWindows = isUnix() ? false : true

                    // Comando de compilação
                    def buildCommand = isWindows ? 'mvn clean package' : 'mvn clean package &'

                    // Executar o comando
                    sh buildCommand
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Publicar o JAR ou outros artefatos
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }
    }
}
